Add category linting

diff --git a/.github/actions/lint-extension/action.yml b/.github/actions/lint-extension/action.yml
--- a/.github/actions/lint-extension/action.yml
+++ b/.github/actions/lint-extension/action.yml
@@ -65,6 +65,35 @@ runs:
         fi
       shell: bash
 
+    # Ensures that the manifest.json category is valid
+    - name: Check category
+      run: |
+        # Read in valid category titles from extensions.json
+        VALID_CATEGORY_TITLES=$(jq -c '[.categories[] | .title]' ./extensions.json)
+
+        # Read in category from the extension's manifest.json
+        EXTENSION_CATEGORY=$(jq -r '.extension.category // ""' ./extensions/${{ inputs.extension-name }}/manifest.json)
+
+        # If the extension's category is empty, skip validation
+        if [ -z "$EXTENSION_CATEGORY" ]; then
+          echo "No category specified in manifest.json"
+          exit 0
+        fi
+
+        # Check if extension category is in the valid categories title list
+        CATEGORY_VALID=$(jq -n --argjson global "$VALID_CATEGORY_TITLES" --arg category "$EXTENSION_CATEGORY" '
+          $global | index($category) != null
+        ')
+
+        # Check if the category is valid
+        if [ "$CATEGORY_VALID" != "true" ]; then
+          echo "Error: The category '$EXTENSION_CATEGORY' in manifest.json is not defined in extensions.json"
+          echo "Valid categories are: $(jq -r 'join(", ")' <<< "$VALID_CATEGORY_TITLES")"
+          echo "Please use one of the valid category titles or add a new category to the 'categories' array in extensions.json."
+          exit 1
+        fi
+      shell: bash
+
     # Ensures that the manifest.json has only valid tags
     - name: Check tags
       run: |
